# Generated by Django 5.0.6 on 2024-06-24 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], primary_key=True, serialize=False)),
                ('name', models.CharField(editable=False, max_length=20)),
            ],
            options={
                'verbose_name': 'Month',
                'verbose_name_plural': 'Months',
                'db_table': 'month',
                'indexes': [models.Index(fields=['id'], name='month_id_123636_idx')],
            },
        ),
    ]
