# Generated by Django 5.0.6 on 2024-06-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='month',
            name='month_id_123636_idx',
        ),
        migrations.AlterField(
            model_name='month',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='month',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
