# Generated by Django 5.0.6 on 2024-06-23 23:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daywork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.payment')),
            ],
            options={
                'verbose_name': 'Daywork',
                'verbose_name_plural': 'Dayworks',
                'db_table': 'daywork',
                'indexes': [models.Index(fields=['id'], name='daywork_id_d99b16_idx')],
            },
        ),
    ]
