# Generated by Django 5.0.6 on 2024-06-23 23:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payed_at', models.DateTimeField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.FloatField()),
                ('description', models.TextField()),
                ('month_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payment',
                'indexes': [models.Index(fields=['id'], name='payment_id_fc31a4_idx')],
            },
        ),
    ]
