# Generated by Django 5.0.6 on 2024-06-23 23:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payed_at', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('description', models.TextField()),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payment',
                'indexes': [models.Index(fields=['id'], name='payment_id_fc31a4_idx')],
                'unique_together': {('date',)},
            },
        ),
    ]
